---
- name: Converge
  hosts: all
  tasks:
    - name: print out os family
      debug: msg={{ ansible_os_family }}
    - name: Include ansible-role-lunarvim
      include_role:
        name: ansible-role-lunarvim
      vars: 
        with_neovim: true
