---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
  - name: Stat ~/.local/share/lunarvim/lvim
    stat:
      path: ~/.local/share/lunarvim/lvim
    register: lunarvim_exists

  - name: ~/.lunarvim exists
    assert:
      that: lunarvim_exists.stat.exists
